name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest #github nos fornecerá a máquina.
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "777888"
          envkey_POSTGRES_DB: "students_live"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres_sorteador_db_live:5432/students_live"
          directory: back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run NOMECONTAINER npm run test